version: "3"

services:
  emily-pig-piglet-detection-yz4nm7:

    image: emily-pig-piglet-detection-yz4nm7
    container_name: emily-pig-piglet-detection-yz4nm7

    build:
      context: ../../
      dockerfile: ./Dockerfile

    env_file:
      - ./.env
    
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}

    ipc: ${IPC}
    runtime: ${RUNTIME}
    networks:
      - emily-pig-piglet-detection-yz4nm7-network
    
    
networks:
  emily-pig-piglet-detection-yz4nm7-network:
    driver: bridge
    name: emily-pig-piglet-detection-yz4nm7-network